egon:
  replicaCount: 2
  image:
    repository: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/egon
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 9092
    type: ClusterIP

redis:
  host: redis.external-services
