apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "egon.chart" . }}
    app.kubernetes.io/name: {{ include "egon.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceAccountName: egon
  replicas: {{ .Values.egon.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "egon.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "egon.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.egon.image.repository }}:{{ .Values.egon.image.tag }}
        imagePullPolicy: {{ .Values.egon.image.pullPolicy }}
        resources:
          limits:
            memory: 1Gi
            cpu: 300m
          requests:
            memory: 1Gi
            cpu: 300m
        env:
        - name: KAFKA_BROKERS
          value: {{ .Values.kafka.brokers }}
        - name: REDIS_HOST
          value: {{ .Values.redis.host }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
      - name: download-dir
        emptyDir: {}
